### PR TITLE
Add ulog_output_remove, update docs, fix UT bugs, refactor private code

### LINKED ISSUE #110: Documenration refactoring

### PR DESCRIPTION
**Pull request by an-dr**
- Revamp the documentation
- Fix bug of execution prefix callback many times per one logging
- Move topic string after the level string `[Topic] INFO` -> `INFO [Topic]`
- Add 'ulog_output_remove'
- Refactor private functions, reformat the source file

Closes #110

### CODE REVIEW

File: example/main.cpp [hunk 1]
```diff
@@ -5,24 +5,24 @@ It demonstrates basic logging functionality using C interface.
...
-
-    23:55:59.014 ms [Bluetooth] DEBUG main.cpp:57: Bluetooth message 1
-    23:55:59.015 ms [Audio] WARN  main.cpp:62: Audio message 2
-    [User Output:4] 23:55:59.017 ms [Audio] WARN  main.cpp:62: Audio message 2
-    23:55:59.018 ms [Serial] ERROR main.cpp:63: Serial message 1
-    [User Output:5] 23:55:59.020 ms [Serial] ERROR main.cpp:63: Serial message 1
-    23:55:59.021 ms [Serial] FATAL main.cpp:64: Serial message 2
-    [User Output:6] 23:55:59.023 ms [Serial] FATAL main.cpp:64: Serial message 2
+    18:35:28.000 ms TRACE main.cpp:71: Trace message 1
+    18:35:28.001 ms DEBUG main.cpp:75: Debug message 0x2
```
Comment (an-dr) [inline example/main.cpp:9]: Replace "ms" with [ID:N] in the orefix example
