### PR TITLE
Add UTs for topics, locking and prefix, fix found bugs

### LINKED ISSUE #46: Locking

### LINKED ISSUE #49: Add unit tests: Custom Prefix

### LINKED ISSUE #51: Add unit tests: Topics - Static

### LINKED ISSUE #57: `write_formatted_message` with log_target_type:T_BUFFER makes all prints in the buffer beginning overwriting instead of appending
Discovered during #49

### PR DESCRIPTION
**Pull request by an-dr**
- Fix topic levels handling — topics now showed only if they are allowed
- Fix writing to a buffer using `write_formatted_message` — not it writes the whole message

Closes #46, Closes #49, Closes #57, Closes #51

### CODE REVIEW

File: src/ulog.c [hunk 1]
```diff
@@ -659,7 +660,7 @@ void ulog_log(int level, const char *file, int line, const char *topic,
 
         // If the topic is disabled or set to a lower logging level, do not log
         if (!is_topic_enabled(topic_id) ||
-            (_ulog_get_topic_level(topic_id) < ulog.level)) {
+            (level < _ulog_get_topic_level(topic_id))) {
```
Comment (an-dr) [inline src/ulog.c:663]: @mallenbach found this bug during unit testing. Will be fixed, FYI

File: src/ulog.c [hunk 2]
```diff
@@ -81,11 +81,12 @@ static ulog_t ulog = {
...
 typedef struct {
     char *data;
+    unsigned int curr_pos;
     size_t size;
-} span;
+} buffer_descriptor;
 
 typedef union {
-    span buffer;
+    buffer_descriptor buffer;
```
Comment (an-dr) [inline src/ulog.c:89]: Use a pointer?

Comment (an-dr) [reply src/ulog.c:89]: Does not make sense

File: src/ulog.c (hunk 1 above)
Comment (mallenbach) [reply src/ulog.c:663]: Good catch - thanks! At least, we know that unit testing are useful :-).
